name: Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release SemVer:'
        required: true
      update_notes:
        default: "-"
        description: "Update Notes to Release"
        required: true
        
jobs:
  checkout_repo:
    name: "Checkout Repository"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master

  setup_project:
    name: "Setup Project"
    needs: [checkout_repo]
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore OpenLetsPlay

  install_and_update:
    name: "Install zip & update version"
    needs: [checkout_repo]
    runs-on: ubuntu-latest
    steps:
    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" OpenLetsPlay/OpenLetsPlay.csproj"  

  build_and_release:
    name: "Build and Release"
    needs: [setup_project, install_and_update]
    runs-on: ubuntu-latest
    steps:
    - name: Build Project
      run: dotnet build OpenLetsPlay --configuration Release --no-restore
    - name: Zip Artifact
      run: zip -q -r ./OpenLetsPlay.zip OpenLetsPlay/bin/Release/net8.0/*
    - name: Release
      uses: softprops/action-gh-release@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_PRE_RELEASE: ${{ endsWith(github.event.inputs.version, '-alpha') || endsWith(github.event.inputs.version, '-beta') || endsWith(github.event.inputs.version, '-rc') }}
      with:
        body: |
          Notes:
            ${{ github.event.inputs.update_notes }}
        files: ./OpenLetsPlay.zip
        name: OpenLetsPlay v${{ github.event.inputs.version }}
        prerelease: ${{ env.IS_PRE_RELEASE }}
        tag_name: V${{ github.event.inputs.version }}
